Samsung/Universum

CHANGELOG.rst
=>  update(docs): update chage log to Universum 0.17.0

README.md, doc/guide.rst, doc/index.rst, setup.py
=> update(docs): restructure documentation, switch README to Github Markdown

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
=> feat(docs): add community docs

README.md
=> fix(docs): add RtD shield to README file

_universum/lib/utils.py, _universum/modules/vcs/git_vcs.py, _universum/modules/vcs/perforce_vcs.py, universum.py
=> fix(vcs): remove back trace in case of vcs import error

_universum/modules/vcs/vcs.py, tests/test_vcs.py, universum.py
=>  feat(vcs): remove setting default VCS type to p4

tests/git_utils.py, tests/perforce_utils.py, tests/test_p4_revert_unshelved.py, tests/test_vcs.py, tests/utils.py
Removed unused work_dir and commited_change from perforce_workspace fixture.
Refactored and simplified test_p4_c_and_revert.
Did minor polishing in VCS test.
=> refactor(test): rename root_directory in environment classes

_universum/lib/utils.py, _universum/modules/launcher.py, _universum/modules/vcs/perforce_vcs.py, tests/git_utils.py, tests/perforce_utils.py, tests/test_unicode.py, tests/utils.py
Also fixed several bugs related to paths with unicode characters
=> feat(test): add unicode paths tests

tests/deployment_utils.py, tests/perforce_utils.py, tests/test_deployment.py, tests/test_integration.py, tests/utils.py
=> feat(tests): reuse deployment containers in PyCharm

_universum/modules/automation_server/teamcity_server.py, _universum/modules/launcher.py, _universum/modules/vcs/git_vcs.py, _universum/modules/vcs/local_vcs.py, _universum/modules/vcs/perforce_vcs.py, _universum/submit.py, tests/test_argument_check.py
Jenkins checks are not fixed, because they require
splitting AutomationServer, BaseServer and JenkinsServer
into separate modules for "poll" and "main" modes.
This change is made in scope of task #271.
=> fix(universum): incorrect checks of parameters

_universum/modules/automation_server/teamcity_server.py, _universum/modules/launcher.py, _universum/modules/vcs/perforce_vcs.py, _universum/submit.py
This change contributes to #271.
=> update(universum): improve error messages for incorrect parameters

_universum/modules/vcs/gerrit_vcs.py, _universum/modules/vcs/git_vcs.py, _universum/modules/vcs/swarm.py, tests/test_argument_check.py
=> feat(test): implement all tests for argument checks

_universum/lib/module_arguments.py, universum.py
Also did some refactoring inside the module_arguments.py.
=> Move handling of "default" subcommand to module_arguments.py

CHANGELOG.rst, _universum/__init__.py
0.18.0 instead of 0.17.1 because of breaking change
=> update(docs): update change log to Universum 0.18.0

_universum/__init__.py
Update master version to be ahead of release branch to avoid possible version confusion
=> update(docs): update version

README.md, doc/prerequisites.rst
=> update(docs): add installation guide for Universum to README

README.md
In scope of #237 
Work in progress
=> update(docs): add architecture overview to README file

README.md
In scope of #237 
Work in progress
=> update(docs): add actual architecture overview to previous contents list

universum.py
Resolves #183 
Also applies to #174
=> feat: add Universum version as log identifier for Jenkins plugin

_universum/modules/artifact_collector.py
Resolves #326
But please note that according to [zipfile documentation](https://docs.python.org/2/library/zipfile.html#zipfile-objects)
> default zip and unzip commands on Unix (the InfoZIP utilities) don’t support ZIP64 extensions
=> fix(artifacts): rewrite 'make_archive' to use ZIP64 extentitions

_universum/modules/output/output.py, _universum/modules/output/terminal_based_output.py
=> fix(output): remove outdated Jenkins plugin block labels

_universum/__init__.py, _universum/lib/utils.py, _universum/modules/vcs/git_vcs.py, _universum/modules/vcs/github_vcs.py, _universum/modules/vcs/swarm.py, _universum/modules/vcs/vcs.py, tests/conftest.py, tests/deployment_utils.py, tests/test_argument_check.py, tests/test_report.py
WIP
Resolves #241 
Example: https://github.com/k-dovgan/test/pull/1/checks
=> GitHub reporter

_universum/modules/vcs/github_vcs.py
Relates to #241 
See https://github.com/k-dovgan/test/pull/2/files
=> feat(github): add inline comments for code_report

universum_log_collapser/pom.xml, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/AnnotatorFactory.java, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Note.java, universum_log_collapser/src/main/resources/index.jelly, universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js, universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/style.css
feat(jenkins_plugin): upload Jenkins plugin sources
=> feat(jenkins_plugin): upload Jenkins plugin sources

universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js
fix(jenkins_plugin): logic to update page content on long steps executing
=> fix(jenkins_plugin): logic to update page content on long steps executing

_universum/lib/utils.py, _universum/modules/vcs/perforce_vcs.py, tests/perforce_utils.py, tests/test_p4_revert_unshelved.py, tests/utils.py
=> fix(p4): pass only expected exceptions on file revert

.gitignore, universum_log_collapser/.gitignore, universum_log_collapser/pom.xml
feat(jenkins_plugin): increase version, update gitignore with plugin-specific files
=> feat(jenkins_plugin): increase version, update gitignore with plugin-specific files

tests/test_integration.py, universum.py
=> fix(universum): handle SIGTERM properly

universum_log_collapser/pom.xml, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js
=> fix(jenkins_plugin): fix first section expand/collapse on pipeline job

universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js
feat(jenkins_plugin): expand failed steps by default
Resolves #356
=> feat(jenkins_plugin): expand failed steps by default

universum_log_collapser/pom.xml, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/AnnotatorFactory.java, universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/LogActiveTest.java, universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/SectionsTest.java, universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/TestSuite.java
test(jenkins_plugin): Java tests for sections handling added
Resolves #358
=> test(jenkins_plugin): Java tests for sections handling added

_universum/modules/launcher.py, doc/args.rst, tests/test_integration.py, tests/test_run_steps_filter.py
Add flag '--run-step' to filter steps which should be executed.
Resolves #363
=> Add flag to filter steps which must be executed

tests/docker/universum_test_env/Dockerfile, tests/docker/universum_test_env_no_p4/Dockerfile, tests/docker/universum_test_env_no_vcs/Dockerfile
=> fix: docker images. Update ubuntu version, use python3.7 instead 2.7

tests/configs.py, universum_log_collapser/.gitignore, universum_log_collapser/e2e/live_log_html.test.js, universum_log_collapser/e2e/static_html.test.js, universum_log_collapser/e2e/universum_live_log_to_html.py, universum_log_collapser/e2e/utils.js, universum_log_collapser/plugin/pom.xml
=> test(jenkins_plugin): add JS tests on generated HTML

_universum/modules/vcs/perforce_vcs.py
=> fix(p4): delete CLs too in case of force clean

_universum/modules/launcher.py
=> fix(launcher): change exec syntax to one supported by Python 2.7.6

tests/test_multiline_variables.py, universum/lib/module_arguments.py, universum/lib/utils.py, universum/modules/vcs/github_vcs.py
Also fix bug with 'metavar' and non-existing help in ModuleArgumentParser and deprecated 'iteritems' in github_vcs
=> feat(args): add multiline variable type

doc/args.rst, doc/args_github_handler.rst, universum/__main__.py
Somehow currently NOT working; under investigation
=> feat(docs): add documentation page for github-handler

doc/conf.py
=> fix(docs): limit nav panel depth to remove confusing subparagraphs

tests/conftest.py, tests/test_code_report.py, tests/utils.py, universum/modules/code_report_collector.py
Added iteration to not only replace in 'artifacts', but in 'report_artifacts' and generally anywhere applicable.
Resolves #286
=> fix(code_report): replace code report pseudo-variable not only in command

universum/github_handler.py, universum/lib/utils.py, universum/modules/automation_server/jenkins_server.py, universum/modules/vcs/gerrit_vcs.py, universum/modules/vcs/github_vcs.py, universum/modules/vcs/swarm.py
=> fix(swarm): update outdated error handling for HTTP errors

tests/test_p4_exception_handling.py, tests/test_regression.py, universum/modules/vcs/base_vcs.py
=> fix(vcs): raw exceptions are shown during finalize

tests/deployment_utils.py, tests/test_code_report.py, tests/test_regression.py, universum/main.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/perforce_vcs.py, universum/modules/vcs/vcs.py
=> fix(vcs): exception if vcs is 'none' and there are code report steps

tests/test_argument_check.py, universum/__main__.py, universum/modules/error_state.py, universum/modules/launcher.py, universum/modules/vcs/local_vcs.py, universum/modules/vcs/vcs.py
This version only implements reporting multiple errors for the following parameters:
- vcs type
- config path
- source path for local VCS
The idea is to commit this version and then gradually move the entire code base to this approach.
=> feat(args): initial version of reporting multiple errors

universum/main.py, universum/modules/artifact_collector.py, universum/modules/code_report_collector.py, universum/modules/structure_handler.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/git_vcs.py, universum/modules/vcs/perforce_vcs.py, universum/modules/vcs/vcs.py
Add type annotations to 'main' and then resolve all missing dependencies
Some refactoring was needed
Existing tests are sufficient
=> refactor: type annotations

tests/test_poll.py, universum/poll.py
=> fix(poll): exception if polling with local vcs

CHANGELOG.rst, doc/prerequisites.rst
=> update(docs): update change log to Universum 0.19.0

tests/test_argument_check.py, tests/test_multiline_variables.py, universum/github_handler.py, universum/lib/utils.py, universum/modules/error_state.py, universum/modules/vcs/github_vcs.py
Moved read_and_check_multiline_option function from utils to
HasErrorState. Improved error messages text.
=> feat(args): print multiple errors in github

universum_log_collapser/universum_log_collapser/pom.xml, universum_log_collapser/universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/SectionsTest.java
=> fix(jenkins_plugin): fix invisible 'Failed' step results at timestamps plugin usage

universum_log_collapser/universum_log_collapser/pom.xml, universum_log_collapser/universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/LogActiveTest.java
=> fix(jenkins_plugin): fix plugin stop at non-indented line

tests/deployment_utils.py, tests/test_integration.py
The issue is caused by nonci mode test leaving file named "file" in
working directory
=> fix(tests): issue with steps failing in PyCharm

doc/args.rst, doc/args_github_handler.rst, doc/args_nonci.rst, doc/args_poll.rst, doc/args_submit.rst, doc/code_report.rst, doc/conf.py, doc/configuring.rst, doc/github_handler.rst, doc/guide.rst, doc/index.rst, doc/init.rst, doc/teamcity.rst
=> refactor(docs): add replacing {python} with actual Python version

tests/test_argument_check.py, universum/config_creator.py, universum/modules/launcher.py
=> feat(launcher): add default config name

universum_log_collapser/e2e/test.html, universum_log_collapser/universum_log_collapser/pom.xml, universum_log_collapser/universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js
=> fix(jenkins_plugin): handle failed steps items array properly

universum_log_collapser/universum_log_collapser/pom.xml, universum_log_collapser/universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/SectionsTest.java
=> feat(jenkins_plugin): support simplified log

tests/test_p4_exception_handling.py, tests/test_regression.py, tests/utils.py, universum/lib/utils.py
=> fix(p4): wrong decoding of a byte string

universum/configuration_support.py
=> fix(docs): add notice on filename expansion

universum_log_collapser/universum_log_collapser/pom.xml
Make ant version bump properly.
See https://github.com/Samsung/Universum/pull/564.
=> chore(jenkins_plugin): bump ant version properly

CHANGELOG.rst, doc/additional_commands.rst, doc/github_handler.rst, doc/guide.rst
=> fix(docs): fix broken links

universum/configuration_support.py
unify used language
explain benefit of new API
add examples w/ warning checks
=> fix(docs): clarify configuration docs

doc/_static/theme_overrides.css
Compare:
https://universum.readthedocs.io/en/latest/configuration_support.html
and
https://universum.readthedocs.io/en/fix-field-list/configuration_support.html
=> fix(docs): fix 'field list' captions in :class: descriptions

Makefile, tests/test_integration.py, tests/test_regression.py, tests/utils.py, universum/modules/api_support.py, universum/modules/artifact_collector.py
Also add fixes for updated Pylint warnings
=> fix(test): Jenkins logs are not redirected to files by default

.universum.py, tests/test_code_report.py, universum/analyzers/mypy.py
add mypy analyzer wrapper
use wrapper internally in config
refactor analyzer test cases for extensibility
=> feat(analyzer): add mypy

doc/code_report.rst
remove svace as unsupported
minor fix in uncrustify example by customer request
=> fix(docs): remove svace from documentation

tests/test_multiline_variables.py, universum/github_handler.py, universum/modules/error_state.py, universum/modules/vcs/github_vcs.py
This option is actually never used and not recommended for usage
=> refactor(args): remove reading from stdin support

tests/test_submit.py, tests/test_unicode.py, universum/lib/utils.py, universum/modules/error_state.py, universum/submit.py
=> feat(submit): add file arguments support

README.md
=> fix(docs): wrong venv path in README

tests/test_code_report.py, universum/modules/code_report_collector.py
=> fix(code_report): make config processing recursive

.gitignore, README.md, setup.py, tests/test_html_output.py, universum/__main__.py, universum/modules/artifact_collector.py, universum/modules/output/base_output.py, universum/modules/output/html_output.py, universum/modules/output/output.py
1. New `--html-log` flag and its processing added
2. Simple tests added
3. New dependencies for tests added to README and setup.py
=> feat(output): init HTML output feature

noxfile.py, tests/conftest.py, tests/deployment_utils.py, tests/git_utils.py, tests/test_argument_check.py, tests/test_integration.py, tests/test_p4_exception_handling.py, tests/test_p4_revert_unshelved.py, tests/test_regression.py, tests/test_run_steps_filter.py, universum/config_creator.py, universum/lib/module_arguments.py, universum/modules/automation_server/jenkins_server.py, universum/modules/automation_server/teamcity_server.py, universum/modules/output/teamcity_output.py, universum/modules/structure_handler.py, universum/modules/vcs/git_vcs.py, universum/modules/vcs/github_vcs.py, universum/modules/vcs/local_vcs.py, universum/modules/vcs/perforce_vcs.py, universum/modules/vcs/swarm.py, universum/modules/vcs/vcs.py, universum/poll.py
Replace .format() with f-strings
Remove excessive 'global' usage
=> refactor(style): apply changes proposed by Pylint

README.md, tests/deployment_utils.py, tests/perforce_utils.py, tests/test_regression.py, tests/utils.py
=> feat(test): add a variable to cache docker containers outside PyCharm

tests/test_html_output.py, universum/modules/output/html_output.py
=> feat(output): section title and status coloring in HTML output

universum/modules/vcs/perforce_vcs.py
=> fix(p4): merge/resolve unshelved changelists instead of forcibly rewriting one another

universum_log_collapser/e2e/package-lock.json, universum_log_collapser/e2e/package.json
Dependabot was not able to create an automated update.
See details here: https://github.com/Samsung/Universum/security/dependabot/universum_log_collapser/e2e/package-lock.json/set-value/open
=> fix(plugin): dependabot reported this vulnerability

tests/test_html_output.py, universum/modules/output/html_output.py
=> feat(output): timestamps in HTML log

tests/test_p4_exception_handling.py, universum/modules/launcher.py, universum/modules/vcs/perforce_vcs.py
Test for sh output handling is now redundant
=> fix(p4): switch sh diff to p4python

universum/configuration_support.py, universum/modules/launcher.py
=> feat(config): add path to configuration file to configuration_support

doc/additional_commands.rst, doc/args.rst, doc/filter_description.rst
=> fix(docs): add reference to filter usage in non-CI

universum/lib/utils.py, universum/modules/artifact_collector.py, universum/modules/structure_handler.py, universum/modules/vcs/perforce_vcs.py, universum/poll.py
Changed all usages of run_in_block to context manager and 'with' block
=> refactor(structure): remove run_in_block function

universum/configuration_support.py, universum/modules/artifact_collector.py, universum/modules/automation_server/automation_server.py, universum/modules/automation_server/github_server.py
Automation server for Github Actions
Resolves #(issue)
Start build on Github actions and report build results to review
=> Github Action automation server

universum/modules/reporter.py
Add options to print falis_only short report (print only real failed steps)
Resolves #(issue) None
=> Fails only short report

doc/github_actions.rst, doc/github_handler.rst, doc/index.rst
Add GitHub Actions docs
Resolves #(issue)
None
Build docs
=> feat(doc): add GitHub Actions docs

tests/test_integration.py, universum/modules/reporter.py
=> feat(report): return non-zero exit code if any step fails

tests/test_conditional_steps.py, universum/modules/structure_handler.py
Before this PR - both branch steps (`if_succeeded` & `if_failed`) should be set to a conditional step for the correct work.
=> feat(structure_handler): allow one branch step to be set in the conditional step

tests/test_conditional_steps.py
=> test(artifact_collector): report artifacts for conditional steps

tests/test_preprocess_artifacts.py, tests/utils.py
As some additional infrastructure code is needed, other tests will be added in further PRs to reduce the current change size.
=> test(artifact_collector): basic tests for the set_and_clean_artifacts() logic

.github/workflows/precommit-check.yml, tests/test_argument_check.py, tests/test_git_poll.py, tests/test_integration.py, tests/test_preprocess_artifacts.py, tests/utils.py, universum/analyzers/utils.py, universum/configuration_support.py, universum/lib/utils.py, universum/modules/artifact_collector.py, universum/modules/reporter.py, universum/modules/vcs/perforce_vcs.py, universum/modules/vcs/vcs.py
Also turn on failing on failed steps for better GhA reporting
=> fix(checks): MyPy and Pylint warnings

tests/test_preprocess_artifacts.py
=> test(artifact_collector): preprocessing artifacts in the 'artifacts' directory

universum/analyzers/uncrustify.py
Fixed the following issues in uncrustify analyzer:
- issue with not finding the formatted file if if was passed to the
analyzer by using absolute path
- issue with not initializing variables leading to exception if their
value are not found in uncrustify config file
- issue with not handling all variants of the uncrustify config file
formatting
=> fix(uncrustify): usability issues

.github/workflows/telegram-bot.yml
Also fix typo and add comment on closed review
=> feat(github): add comments on approve changes

doc/configuring.rst, pylintrc, tests/test_argument_check.py, tests/test_conditional_steps.py, tests/test_git_poll.py, tests/test_integration.py, tests/utils.py, universum/analyzers/utils.py, universum/configuration_support.py, universum/lib/utils.py, universum/modules/artifact_collector.py, universum/modules/output/terminal_based_output.py, universum/modules/reporter.py, universum/modules/structure_handler.py, universum/modules/vcs/perforce_vcs.py, universum/modules/vcs/vcs.py
Fix pylint, mypy, and doctest issues on the outdated `conditional_steps` branch for easier merge with the master branch in the next PR.
Most of pylint & mypy fixes were taken from [this](https://github.com/Samsung/Universum/commit/994f21804a96ddee6ec45a112bb5d8ab499f8327) commit.
Some additional fixes were added in structure_handler.py & test_conditional_step.py to cover code, specific for the `conditional_steps` branch.
=> fix: pylint, mypy, doctest issues

universum/modules/reporter.py
Fix merge errors that were done in [this](https://github.com/Samsung/Universum/commit/b7890adc07aaae0a52581aa9c42783776cb452c5) commit without CI check.
=> fix: merge errors

universum/configuration_support.py
Replaced test of truthiness with an explicit check of None value
Resolves #764 
Tested by doctests
=> fix(configuration):  allow False value for Step

doc/configuring.rst, tests/test_conditional_steps.py, universum/configuration_support.py, universum/modules/artifact_collector.py, universum/modules/structure_handler.py
Fixing one of the previous PR comments - https://github.com/Samsung/Universum/pull/737#discussion_r987590730.
Tests extension will be prepared in a separate PR.
Re-apply changes from https://github.com/Samsung/Universum/pull/796.
=> feat(configuration_support): change conditional branch steps type to Configuration

tests/test_conditional_steps.py
Postponed tests update for https://github.com/Samsung/Universum/pull/808 change.
=> test(configuration_support): test Step->Configuration update for conditional step branches
