Samsung/Universum

universum.py
Previous implementation of simulated default subparser performed
adding the word "default" at incorrect position in the argument list
because it used length of the entire arguments tuple, not the length
of the first element, which is a list of command-line parameters.
=> fix(test): fix impossibility to launch universum main with arguments

tests/configs.py
We didn't state this option as it is used by default; but some systems have different configurations
=> fix(configs): unify usage of site packages

tests/test_p4_revert_unshelved.py, tests/utils.py
`create_settings only` creates empty set of settings.
Because of that changed the name to `create_empty_settings`.
Also, the settings switching based on class is not needed,
changed the code to depend on test type.
=> fix(test): rename create_settings

_universum/modules/artifact_collector.py, _universum/modules/automation_server/automation_server.py, _universum/modules/automation_server/base_server.py, _universum/modules/automation_server/jenkins_server.py, _universum/modules/automation_server/local_server.py, _universum/modules/automation_server/teamcity_server.py, _universum/modules/launcher.py, _universum/modules/reporter.py, _universum/poll.py
A single automation server was used by two universum modes:
main and poll. This led to incorrect help message
shown and to inability to check respective options
independently.
With this change applied it is now possible to correctly
display help for command-line parameters and check their
correctness.
=> refactor(automation server): split module into parts

_universum/lib/utils.py, _universum/modules/automation_server/teamcity_server.py, _universum/modules/vcs/perforce_vcs.py, _universum/modules/vcs/swarm.py, tests/test_argument_check.py
Previous implementation of check_required_option led
to too short unclear error messages. Fixed by adding
more details and explanations in all places, where it
was used.
This change is made in scope of task #271.
=> feat: fix usage of check_required_option

tests/test_integration.py
Previous test could pass due to error in the test itself.
=> feat(test): add positive cases for empty arguments test

_universum/modules/launcher.py
Since logs are only accessible as artifacts after build, printing them to console is more convenient.
=> feat(launch): change default Launcher output to terminal for Jenkins builds

universum_log_collapser/pom.xml, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java
fix(jenkins_plugin): fix log displaying at job terminating
There is no specific log line, which can indicate that job is stopped unexpectedly and following log is not Universum log. That's why skipping log processing, if some log without indentation appears in place were it should be with indentation.
Normal log example:
```
|  step data...
|  step data...
|  step data...
```
Terminated log example:
```
|  step data...
|  step data...
Terminated
Build was aborted
```
Resolves #348 
Interrupt Jenkins build with Universum inside in various configuration and time moments.
=> fix(jenkins_plugin): fix log displaying at job terminating

tests/configs.py, universum_log_collapser/.gitignore, universum_log_collapser/pom.xml, universum_log_collapser/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/AnnotatorFactoryTest.java, universum_log_collapser/src/test/java/io/jenkins/plugins/universum_log_collapser/LogActiveTest.java
1. Java tests for log start, end and break added.
2. Make regexps for log end more specific.
3. Move processing of Jenkins log end to top of the function, because it was skipped as "non-Universum log".
Relates to #358
=> test(jenkins_plugin): add Java tests for log start, end, break

universum_log_collapser/plugin/pom.xml
Plugin was buildable, but did nothing after installation on Jenkins server.
This issue appeared after directories structure changes. "artifactId" field in pom.xml should be the same as project directory name.
Build plugin (`mvn package`) and install "plugin.hpi" on Jenkins server.
=> fix(jenkins_plugin): fix incorrect artifactId after directories structure change

universum_log_collapser/plugin/pom.xml, universum_log_collapser/plugin/src/main/java/io/jenkins/plugins/universum_log_collapser/Annotator.java, universum_log_collapser/plugin/src/test/java/io/jenkins/plugins/universum_log_collapser/TestSuite.java
When "Timestamper" plugin is enabled on Jenkins server, plugin stops collapsing.
Fixed by changing text string for regexps parsing. `text.getText()` will return raw Universum text without any wrapping tags.
=> fix(plugin): fix collapsing with timestamps plugin usage

doc/args.rst
Online documentation of **Universum 0.18.3** for flag **--filter** contain *console help* content. However it should contain another – extended description.
=> fix(doc): incorrect flag name

universum_log_collapser/e2e/static_html.test.js, universum_log_collapser/e2e/test.html, universum_log_collapser/plugin/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js
Universum step name can be wrapped by <span> or not. Span absence is crashing JS code, which leads to stopping steps coloring after step without <span>.
Example:
```
<label for="hide-block-3">
<span class="sectionLbl">
<span style="color: #1E90FF;">
3. Step name
</span>
</span>
</label>
```
or
```
<label for="hide-block-3">
<span class="sectionLbl">
3. Step name
</span>
</label>
```
=> fix(jenkins_plugin): fix JS crash at steps coloring

_universum/modules/launcher.py
The regression was introduced by the previous fix of the exec statement for python 2.7.6 on Ubuntu 14.4. Parentheses were accidentally removed by the exec statement fix.
Also removed using of locals dictionary in this commit, as it is not needed by the previous fix of exec.
=> fix(launcher): incorrect syntax in read call

tests/configs.py
'--system-site-packages' usage can lead to misscheck of dependencies defined in setup.py. For more information see appropriate flag documentation.
'upgrade' flag requires to test Universum using latest versions of packages.
=> fix(ci): config didn't verify dependencies correctly

tests/perforce_utils.py, tests/test_p4_submit.py, tests/test_submit.py, tests/test_vcs.py
=> add(test): submit to protected branches

_universum/modules/launcher.py, doc/code_report.rst, doc/configuring.rst, setup.py, tests/test_api.py, tests/test_code_report.py, tests/test_integration.py, universum.py
reason: python3 uses UTF-8 by default.
'#!/usr/bin/env python3' not requires to run Universum but cause issue
when file saved with 'windows' line ending.
=> fix: tests

_universum/modules/vcs/perforce_vcs.py, tests/test_p4_exception_handling.py, tests/test_p4_revert_unshelved.py
This change fixes the rare bug, happening when files to be reverted by `finalize()` function are no longer accessible by P4. This might be a result of two scenarios:
1. actions done by Universum steps (e.g. `chmod` command in scripts)
2. desirable workspace name passed to Universum corresponds to a workspace that already exists and user running the Universum has no right to change files to be reverted in this workspace
=> fix(p4): reverted files may no longer be accessible

_universum/modules/vcs/perforce_vcs.py, tests/test_submit.py
If any changes are already checked out in default CL, they will be ignored.
If submitting fails, restoring all changes is guaranteed.
Resolves #388
Resolves #162
=> fix(submit): create and delete real CL instead of using default

_universum/modules/vcs/perforce_vcs.py
Old command `p4 revert -C <client> //...` reverted all CLs in workspace.
Unfortunately, this command doesn't seem to work for non-admin users,
returning `[Error]: "You don't have permission for this operation."`
Reverting all CLs separately still works though.
=> fix(p4): one revert for whole client is admin only

tests/test_nonci.py
The reason of the failure is that 'sh' changed the format of the
command line string returned for the launched process, and the
test is designed to check exactly one format.
Fixed the failure by avoiding checking of the command line
presence in logs at all.
Also, improved the test to check more features of the nonci mode.
=> fix(test): nonci test started to fail due to 'sh'

tests/test_integration.py, universum.py, universum_log_collapser/e2e/universum_live_log_to_html.py
After fresh installation of python 3.7 on Ubuntu 18.04 from the
'deadsnakes' ppa, the 'python' command launches python version 2.
Version 2 failed to parse universum sources for version 3.
Also fixed shebangs according to linux recommendations.
=> fix(test): bug with launching python2

_universum/modules/vcs/git_vcs.py, tests/git_utils.py
According to the documentation, to change config, user must
either explicitly call 'release' method or use context
managers.
=> fix(git): git module changed API in python 3

tests/deployment_utils.py
In python 3 pytest changed its api for checking of custom marks.
=> fix(test): bug with nonci always False

.gitignore
pip 20.1 doesn't copy files to temp directory for building
package. This leads to build artifacts appearing in the
sources directory.
=> fix(build): add build artifacts to .gitignore

analyzers/pylint.py
The default versions of python depending on the version of
Ubuntu are listed below:
| Ubuntu code name  | Version | Python version |
| ----------------- | :-----: | :------------: |
| Precise Pangolin  |  12.04  |     3.2.3      |
| Quantal Quetzal   |  12.10  |     3.2.3      |
| Raring Ringtail   |  13.04  |     3.3.1      |
| Saucy Salamander  |  13.10  |     3.3.2      |
| Trusty Tahr       |  14.04  |     3.4.0      |
| Utopic Unicorn    |  14.10  |     3.4.2      |
| Vivid Vervet      |  15.04  |     3.4.3      |
| Wily Werewolf     |  15.10  |     3.4.3      |
| Xenial Xerus      |  16.04  |     3.5.1      |
| Yakkety Yak       |  16.10  |     3.5.1      |
| Zesty Zapus       |  17.04  |     3.5.3      |
| Aardvark Aardvark |  17.10  |     3.6.3      |
| Bionic Beaver     |  18.04 …
=> feat(pylint): allow selecting exact python version

analyzers/pylint.py, tests/test_code_report.py
Code report test contained checks only for verifying pylint analyzer
module, but it didn’t check the functionality of code report at all.
After fixing the test, it became clear that pylint analyzer doesn’t
produce any reports if there are no isseus. However, code report
always expects reports to be present. Fixed the pylint analyzer to
always produce report, even if there are no issues found.
Also removed code report tests that are producing output to stdout
instead of writing it to files, because code report module cannot
handle such output.
=> fix(test): code report test only checked pylint analyzer

_universum/modules/code_report_collector.py, _universum/modules/launcher.py, tests/test_code_report.py
The code report functionality launches marked steps twice, but in
nonci mode it uses the same sources both times. Therefore, it cannot
compare results and there is no sense to process code report steps
separately. In addition, currently there is no way to report code
report results in nonci mode, because vcs and code review systems
are not used.
Also removed "afterall" key from generated steps in code report.
This key is not used anywhere.
=> fix(nonci): remove code report from nonci

tests/docker/perforce/run.sh
perforce has changed the structure of its log directories and 'tail'
command produces the error message in an endless loop. Because of
that, if the container is already started and tests attempt to reuse
it, it takes too much time to parse an enormous log. This happens
when running tests from the PyCharm.
Fixed by using correct path to logs file. Also, lowered the verbosity
level to 1. The default level is 3 and it produces too much logs.
=> fix(test): perforce container starts slowly

tests/deployment_utils.py
When running tests from PyCharm there is no need to gather test
coverage.
=> fix(test): do not gather coverage to improve performance

tests/deployment_utils.py
seccomp filters syscalls that are available for applications inside
container. However, we use containers for testing only, so this added
security is not needed. At the same time, it significantly slows down
running of tests.
=> fix(test): disable seccomp to improve performance

setup.py, tests/deployment_utils.py, tests/test_api.py, tests/test_code_report.py
While transferring from Python2.7 to Python3.7 entry points interfere with each other. Will be turned on later.
=> hotfix: temporally disable entry points

tests/deployment_utils.py, tests/test_nonci.py, universum/__main__.py, universum/modules/launcher.py, universum/nonci.py
By default in standard mode project root is set to 'temp'
subdirectory in current directory. But for nonci mode it
doesn't make sense. Implemented setting project root to
current directory if user does not specify this parameter.
=> feat(nonci): set project root to current directory

universum_log_collapser/e2e/package-lock.json, universum_log_collapser/e2e/package.json
Without explicit dependency javascript test fails with the following
error:
stderr: Error: Cannot find module 'jest-cli/bin/jest'
=> fix(test): js test fails due to missing jest-cli module

universum/modules/reporter.py
If the build is successful and the option to report build start and
report successful build are not set, the 'text' variable becomes None.
However, it is then concatenated with other string and this results in
an exception thrown.
Fixes #449
=> fix(report): error message with successful build

doc/prerequisites.rst, setup.py, universum/__main__.py, universum/modules/vcs/github_vcs.py
Also specify vcs-related requirements in 'setup.py': package 'cryptography' has its own dependency on 'cffi', so installing 'cryptography' will also install 'cffi'. However, installing 'cffi' alone is not enough for correct module work.
=> refactor(github_vcs): move non-mandatory import to __init__

configs.py
Done in scope of #361; though detecting and processing by Universum interactive progress bars doesn't actually seem possible at the moment
=> fix(configs): remove pip progress bars (requires pip>=10)

universum/modules/vcs/perforce_vcs.py
It seems that an expired session might still return True for p4.connected()
In scope of #471
=> fix(p4): add disconnect before any connect

tests/test_integration.py, tests/test_multiline_variables.py, universum/lib/utils.py
1. test_abort and test_multiline failed if Universum is not installed
* Added PYTHONPATH environment variable to multiline test and fixed
python command line for abort test
2. "-s" option of the pytest led to the hang up of third invocation of
the test script in the multiline test
* Explicitly provided empty input in the third invocation
3. multiline test failed in PyCharm
* Known bug (https://youtrack.jetbrains.com/issue/PY-40035)
* Implemented workaround by changing sys.stdin.read() to
sys.stdin.readlines()
=> fix(tests): multiple minor issues with pytest and PyCharm

tests/deployment_utils.py, tests/test_deployment.py, tests/test_integration.py, tests/test_nonci.py, universum/__main__.py, universum/analyzers/pylint.py, universum/analyzers/uncrustify.py
Resolves #214 as no longer applicable
We remove shebangs as Universum is no longer recommended to be run as a script (as in `./universum/__main__.py`).
Recommended way instead is running it via `python3.7 -m universum`, to fix the entry point issues (such as not being able to pass exit codes), and also to make used python version clear to user.
We replace absolute imports with relative as they were only needed for script launching to work, and caused a very non-obvious scenario for developing, when a main module launched locally imported installed version of `universum` folder instead of local (and presumably changed) one.
=> fix: remove shebangs and absolute imports

configs.py, setup.py, universum/lib/gravity.py, universum/lib/module_arguments.py, universum/modules/structure_handler.py, universum/modules/vcs/git_vcs.py, universum/modules/vcs/vcs.py
Without the fix, checking 'main' using mypy generates some errors. With the fix the only remaining errors are due to lack of static type annotations in the dependencies (third-party libraries).
To make static analysis of 'vcs' module meaningful, some minor refactoring was needed.
Also, added static type annotations highlighted some missing dependencies in 'git_vcs'.
!!! Please note that no tests have been run yet - this is preliminary pull request for some early feedback.
=> refactor: add type annotations to gravity module

universum/lib/gravity.py, universum/submit.py
The Dependency class was annotated as using the same type for both
source and and target module of the dependency. Because of this
incorrect annotation, mypy produces the error at the place in the code,
where the source module calls the factory to construct the target
module.
Fixed by using two distinct type variables: one for source and one for
target.
Also, added type annotation in one method in submitter to properly
demonstrate the issue.
=> fix(gravity): incorrect type in Dependency

tests/test_argument_check.py
The new test makes sure that the error message for the missing parameter
is displayed only when that parameter is actually missing.
=> test(args): correctness of error messages

tests/test_argument_check.py, universum/modules/error_state.py, universum/modules/vcs/perforce_vcs.py, universum/submit.py
Also removed tests with deleting fields from settings objects. If the
fields is absent, the error state mechanism is able to detect it and
remember the error. However, the code in the module still can access the
field. Such accesses result in exceptions raised from gravity.
This is not an issue for normal operation, because when user launches
the script, all settings fields are present.
=> feat(args): printing multiple errors in p4, submit

tests/deployment_utils.py, tests/test_integration.py, tests/test_nonci.py
Before this fix the artifacts directory was not specified for nonci
tests running in docker. This resulted in universum automatically
calculating it as ‘artifacts’ subdirectory of the current directory,
which is root (“/”). This is confusing and also results in artifacts
missing in a proper place.
Fixed by always specifying artifacts directory for running universum in
docker by using ‘-ad’ command-line parameter. Also fixed artifact checks
in tests accordingly.
=> fix(test): set artifacts dir for nonci tests

pytest.ini, tests/test_argument_check.py
During tests execution, the pytest produces the warning regarding future
change of the default format of the junit report. The solution is to
explicitly set the format. Fixed by setting the format to the new
version.
Also fixed the warning caused by the regular expressions.
=> fix(test): warning produced during pytest run

tests/test_argument_check.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/swarm.py, universum/modules/vcs/vcs.py
Fixed the check for error state in 'MainVcs’ module. If the check is implemented
for error state, as it was before, the code doesn’t try to construct the code
review module in case of any errors across the entire universum. As the result,
there is no check for errors in the parameters of the code review modules and
these errors are not reported to user.
Moved the check for code review and producing error from VCS drivers to the
'MainVcs’ module.
Fixed minor issue with unnecessary try..except block in 'Vcs’ module. In the
past the attempt to access missing vcs type parameter in module settings would
result in AttributeError exception. There were no other sources of this
exception in the code block. However, since there is an explicit check for the
vcs type setting, the try..except block is …
=> feat(args): printing multiple errors in swarm, vcs

doc/args.rst, doc/nonci.rst, universum/__main__.py, universum/config_creator.py
Somehow it doesn't allow empty descriptions any more.
=> refactor(nonci): rename default command to launch nonci

configs.py, doc/code_report.rst, doc/configuring.rst, examples/basic_config.py, examples/configs.py, examples/configs_artifacts.py, examples/configs_background.py, examples/configs_critical.py, examples/if_env_set_config.py, examples/minimal_config.py, tests/perforce_utils.py, tests/test_api.py, tests/test_check_if_env_set.py, tests/test_code_report.py, tests/test_deployment.py, tests/test_integration.py, tests/test_nonci.py, tests/test_p4_exception_handling.py, tests/test_regression.py, tests/test_run_steps_filter.py, tests/utils.py, universum/config_creator.py, universum/configuration_support.py, universum/main.py, universum/modules/artifact_collector.py, universum/modules/code_report_collector.py, universum/modules/launcher.py, universum/modules/structure_handler.py, universum_log_collapser/e2e/universum_config/configs.py
Variations and ProjectConfiguration names are misleading and confusing. 
Variations is a Configuration, which can be added or multiplied with other
Configurations, while ProjectConfiguration is just a description of a single
step. Since there is a conflict with existing Step class, that class has been
renamed too.
The names have been changed as follows:
Step -> RunningStep
ProjectConfiguration -> Step
Variations -> Configuration
=> refactor: rename interface classes

.readthedocs.yml, doc/configuring.rst, setup.py
Actual purpose of this change is to differentiate the 'build step',
that is a `Step` instance, from the 'project configuration',
that is a `Configuration` instance.
=> refactor(docs): update 'configuring'

tests/test_p4_exception_handling.py, universum/modules/vcs/perforce_vcs.py
Resolves #545
First test (and according fix) faces situation of SYNC_CLS variable containing comma, but not containing '@' delimiter.
Second test faces wrong P4Exception re-raise on non-expected errors.
=> fix(p4): make exception handling more user-friendly

tests/test_create_config.py
The reason why `.universum.py` unexpectedly disappeared.
=> fix(test): create-config test interfering with actual config

universum/modules/vcs/perforce_vcs.py
User request due to TeamCity failing build if any blocks fail
=> fix(p4): print warning instead of block failing

tests/test_regression.py, universum/modules/vcs/perforce_vcs.py
Seems that 'client unknown' is enough to stop the whole client cleaning block; while every revert operation should be handled separately, as they all can fail independently.
=> fix(p4): remove empty CL's on force clean

doc/configuring.rst, setup.py, tests/deployment_utils.py, tests/test_api.py, tests/test_integration.py, tests/test_p4_submit.py, universum/analyzers/sarif_report.py, universum/analyzers/scan_build_report.py, universum/analyzers/uncrustify.py, universum/analyzers/utils.py, universum/github_handler.py, universum/lib/gravity.py, universum/lib/module_arguments.py, universum/modules/code_report_collector.py, universum/modules/error_state.py, universum/modules/launcher.py, universum/modules/output/html_output.py, universum/modules/output/teamcity_output.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/github_vcs.py, universum/poll.py, universum/submit.py
1. open() is recommended to use with specific encoding
instead of relying on autodetect
2. list and dict literals are recommended for use instead of
constructors for optimization reasons
3. 'u""' prefix is no longer required, as strings are unicode
by default
=> refactor(pylint): updated according to new recommendations

tests/test_html_output.py, universum/modules/output/html_output.py
Wrapping HTML example:
```
<input type="checkbox" id="1." class="hide">
<label for="1.">
<span class="sectionLbl">1. Section name</span>
</label>
<div>Section body</div>
```
Expected behavior:
* all steps are collapsed at HTML opening
* click on collapsed section name leads to:
- section body is shown, inner sections are collapsed
- section marker changed from `[+]` to `[-]`
* click on not collapsed section name leads to opposite change
=> feat(output): add sections collapsing in HTML output

tests/test_html_output.py, universum/modules/output/html_output.py
=> feat(output): dark mode switch in HTML log

tests/test_html_output.py, universum/modules/output/html_output.py
Coloring "Error:" exceptions prefix in dark read, as it was done in `TerminalBasedOutput`.
=> feat(output): HTML log_exception() coloring

setup.py, tests/test_html_output.py, universum/modules/output/html_output.css, universum/modules/output/html_output.js, universum/modules/output/html_output.py
1. On page open all failed sections and their parents will be automatically expanded.
2. CSS and JS sources moved to separate files to clean up the `HtmlOutput` class
2.1. CSS sources were moved without change
2.2. JS sources were moved from the old plugin and updated to current needs
=> feat(output): expand failed HTML sections

universum/modules/structure_handler.py
According to PEP-484, forward declarations have to be strings.
Applied change implicitly turns all annotations to strings.
=> fix(pylint): allow forward declarations

tests/test_html_output.py, universum/modules/artifact_collector.py, universum/modules/output/html_output.py, universum/modules/output/output.py
**Before**:
1. `python3 -m universum` - HTML log disabled
2. `python3 -m universum --html-log` - HTML log saved to file with the default name 
**Now**:
+ one more option 
3. `python3 -m universum --html-log custom` - HTML log saved to file with the custom name
=> feat(output): parametrize HTML log name

tests/test_run_steps_filter.py, universum/modules/launcher.py
CLI parameters: `... -f 'asdf:!qwer'`
Error message if project config doesn't contain such steps:
```
2. Processing project configs
|   ==> Adding file .../artifacts/CONFIGS_DUMP.txt to artifacts...
|   Error: Project configs are empty, abort
|   Recheck filters applied:
|   	Include patterns: ['asdf']
|   	Exclude patterns: ['qwer']
└ [Failed]
```
=> refactor: update error message if steps filter results are empty

tests/conftest.py, universum/lib/utils.py, universum/modules/automation_server/automation_server.py, universum/modules/output/base_output.py, universum/modules/output/github_output.py, universum/modules/output/output.py, universum/modules/output/terminal_based_output.py
Add Github Actions out type support.
The main goal of these changes is to add support for grouping logs to the Github Action.
At the moment, github does not support nested logs, so the beginning of each new block of logs closes the previous one. 
If the block ends with an error, a error message is displayed.
Resolves #(issue) None
See result on Github Actions:
https://github.com/dogbert911/universum_test/runs/5246061477?check_suite_focus=true
=> Add Github Actions output support

universum/configuration_support.py, universum/lib/gravity.py
Issue:
```
[
{
"symbol": "invalid-name",
"message": "Type variable name \"DictType\" doesn't conform to predefined naming style",
"path": "universum/configuration_support.py",
"line": 439
},
{
"symbol": "invalid-name",
"message": "Type variable name \"ComponentType\" doesn't conform to predefined naming style",
"path": "universum/lib/gravity.py",
"line": 73
},
{
"symbol": "invalid-name",
"message": "Type variable name \"DependencyType\" doesn't conform to predefined naming style",
"path": "universum/lib/gravity.py",
"line": 92
}
][]
```
=> chore: fix pylint 'invalid-name' issues

tests/test_conditional_steps.py, universum/configuration_support.py, universum/modules/launcher.py, universum/modules/structure_handler.py
Initial change for the conditional steps logic, the only basic scenario is implemented and tested. See a newly added test file for a usage example.
Additional logic to handle in the following PRs (which I'm aware of):
- steps addition and multiplying
- steps filtering
- the "critical" flag
- the "if_env_set" flag
- background execution
Please update this list with any ideas to check/implement.
=> feat(structure_handler): initialize conditional steps logic

universum/lib/module_arguments.py
Related to #714, but does not solve it completely.
=> fix(doc): add commentary on default parser

universum/lib/gravity.py, universum/modules/automation_server/base_server.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/github_vcs.py, universum/modules/vcs/local_vcs.py
Surprisingly, new pylint version complains about disable markers because
the corresponding check became disabled by default.
=> fix(pylint): warnings found by new pylint version

universum/modules/launcher.py, universum/modules/structure_handler.py
Refactoring according to [this](https://github.com/Samsung/Universum/pull/718#discussion_r929894902) comment:
> Instead of returning tuple, I suggest to perform some refactoring:
> 
>     1. Declare interface for running step explicitly, as an abstract base class
> 
>     2. Use type declaration of this interface for type checking with mypy
> 
>     3. Include error status into this interface instead of returning it from the "start" and "finalize" functions separately
> 
>     4. Pass the object into active_background_steps instead of passing separate methods
=> refactor(launcher): add RunningStep interface

universum/analyzers/pylint.py
The failure is caused by colorama package producing excessive output at the process
termination. The additional output leads to error when parsing json.
Details:
1. https://github.com/PyCQA/isort/issues/1657
2. https://github.com/tartley/colorama/issues/307
=> fix(test): failure in PyCharm on Ubuntu 22

universum/analyzers/utils.py
When the passed input file is missing, there were no explicit error
message. Instead, the empty list of files to analyze was passed to the
actual analysis tool. As the result, the error message was incorrect and
hard to understand. Fixed by producing warning on each missing input
file and producing error if the final list is empty.
=> fix(analyzer): wrong error on missing input file

doc/index.rst, doc/internal.rst, tests/conftest.py, universum/__main__.py, universum/main.py, universum/modules/code_report_collector.py, universum/modules/launcher.py, universum/modules/output/base_output.py, universum/modules/output/github_output.py, universum/modules/output/html_output.py, universum/modules/output/output.py, universum/modules/output/teamcity_output.py, universum/modules/output/terminal_based_output.py, universum/modules/reporter.py, universum/modules/structure_handler.py, universum/modules/vcs/base_vcs.py, universum/modules/vcs/git_vcs.py, universum/modules/vcs/perforce_vcs.py
1. Reordered and grouped methods, renamed them to make naming consistent. Now names correspond to what methods really do.
2. Added type annotations, documentation and fixed issues found by PyCharm inspections for affected files
3. Made some methods protected
4. Changed interface of the "log_summary_step" (previously report_step) function to make it explicit
=> refactor(output): rename and reorder methods

tests/test_conditional_steps.py, universum/modules/artifact_collector.py, universum/modules/structure_handler.py
This PR contains:
1. Handling conditional step branches artifacts
2. Conditional steps tests update to check files created instead of the log line
Similar changes will be applied to the `configuration.report_artifacts` in the next PR after this change will be reviewed and updated accordingly.
Relates #709
=> feat(artifact_collector): artifacts collection for conditional steps

doc/configuring.rst, universum/configuration_support.py
Relates https://github.com/Samsung/Universum/issues/709
=> docs: conditional steps overview

tests/test_regression.py, universum/main.py, universum/modules/reporter.py
1. Move 'fail_unsuccessful' option that changes program behavior to Main module
2. Change 'pass_errors=False' in result reporting to explicit exception handling for the guaranteed return value
3. Fix bug caused by p.2
4. Fix typing warning
=> fix(report): set exit code even if reporting crashes

universum/modules/vcs/swarm.py
Fixed a copy/paste bug in review version calculation with pass_link
Resolves #(issue) NONE
If your pull request does not include new tests for this change, please describe:
* How to reproduce unwanted behaviour without this fix
* How to make sure your change fixes this unwanted behaviour
* What environment have you been using for your tests
=> fix(SWARM): get review version from pass_link

tests/deployment_utils.py
After some update the docker engine started to require passing full
paths to bind mounts when starting the container.
The issue is reproduced on version 23.0.2. The error message from the
docker engine is the following: "invalid volume specification:
'.work:.work:rw': invalid mount config for type "volume": invalid mount
path: '.work' mount path must be absolute".
=> fix(test): new docker engine version compatibility

universum/modules/code_report_collector.py
Static_analysis_report.json is not used for core report functionality, but is added to artifacts and creates misleading assumption that it has some deeper meaning
As far as I can tell, the only use for it is for debug purposes
Resolves #785
=> fix(report): remove redundant file

.github/workflows/telegram-bot.yml
All previews refer to Universum main page anyway.
=> fix(workflow): disable link previews in TG bot

universum/modules/artifact_collector.py
The `report_artifact_list` variable filling was accidentally removed in the [previous PR](https://github.com/Samsung/Universum/pull/794/). 
It was decided to merge the "artifacts preprocessing" block and the "report artifacts preprocessing" block to simplify the `ArtifactCollector.set_and_clean_artifacts()` method logic.
=> fix(artifact_collector): pre-process artifacts and report artifacts in a single step

setup.py
Latest selenium version is 4.0.9; latest urllib3 version is 2.0.2. However, used selenium version is 3.141, and latest non-failing urllib3 version for running FF with this selenium version is 1.26.15
=> fix(test): outdated dependencies

tests/test_conditional_steps.py, universum/modules/structure_handler.py
Issue fixed: if a sibling step exists after a conditional step, it will be not executed.
=> fix(structure_handler): execute steps after conditinal step

universum/lib/utils.py, universum/modules/vcs/swarm.py
Currently Swarm server returns '404' when adding comments to newly added files in review, causing to report malfunction.
=> fix(swarm): quickfix for incorrect '404' response

tests/test_code_report.py, universum/modules/code_report_collector.py
This change implements support for the SARIF-formatted report files containing the originalUriBaseIds field. 
Those reports include URI split into two records that need additional processing.
Resolves #824
This change was tested locally with the data samples included in the bug #824
=> The originalUriBaseIds field support

README.md, setup.py
This change is intended to fix the issue [#830 Packages are missing during the setup run on the newly deployed system.](https://github.com/Samsung/Universum/issues/830)
Resolves #830 
This change was tested locally on a newly deployed Ubuntu20 system.
To reproduce the #830 issue, please follow the steps mentioned in the Development section and note the following commands are failing:
```
pip3.8 install -U universum[p4]
pip install -U .[test]
```
Those failures are not observed with the proposed changes applied anymore.
=> The README.md and setup.py are updated to install missed dependencies.

tests/test_code_report.py, universum/analyzers/clang_format.py
Resolves [#837](https://github.com/Samsung/Universum/issues/837)
Added creation of directories before opening a file in universum/analyzers/clang_format.py:43
=> fix(clang_format_analyzer): create parent folders for target file

universum/analyzers/utils.py
Used `recursive=True` parameter for glob function to search files by pattern recursively
Resolves [#839](https://github.com/Samsung/Universum/issues/839)
please follow the steps in the [#839](https://github.com/Samsung/Universum/issues/839) issue to confirm the fix
=> fix(analyzers): use recursive glob setting

.github/workflows/telegram-bot.yml
Fix GitHub actions command injection
In the file telegram-bot.yml lines:
```
elif [[ ! -z "${{ github.event.workflow_run }}" && "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
TEXT=`echo -e "<a href=\"${{ env.UNIVERSUM_LOG }}\">Universum run for branch '${{ env.UNIVERSUM_BRANCH }}'</a> <b>SUCCEDED</b>; commit ${{ env.UNIVERUM_COMMIT }} "`
elif [[ ! -z "${{ github.event.workflow_run }}" && "${{ github.event.workflow_run.conclusion }}" == "failure" ]]; then
TEXT=`echo -e "<a href=\"${{ env.UNIVERSUM_LOG }}\">Universum run for branch '${{ env.UNIVERSUM_BRANCH }}'</a> <b>FAILED</b>; commit ${{ env.UNIVERUM_COMMIT }} "`
fi
```
Can be command injection with untrusted env.UNIVERSUM_BRANCH input. See this [PR](https://github.com/Samsung/Universum/pull/841) for example.
An …
=> Fix GitHub actions command injection

.github/workflows/telegram-bot.yml
use UNIVERUM_COMMIT env var in telegram message
Resolves #(issue)
If your pull request does not include new tests for this change, please describe:
* How to reproduce unwanted behaviour without this fix
* How to make sure your change fixes this unwanted behaviour
* What environment have you been using for your tests
=> fix(ci): use UNIVERUM_COMMIT env var in telegram message

tests/test_p4_exception_handling.py, tests/test_poll.py
Fixes for 2 unit tests that fall on CI.
1. `test_p4_error_command_line_wrong_port`
The test expected the error "TCP connect to 127.0.0.1:1024 failed." but the Universum output is: "Connect to server failed; check $P4PORT". The suggested solution is to change the value of `pattern_to_search` in the test.
2. `test_p4_print_exception_wrong_shelve`
The test expected f"Errors during command execution( \"p4 unshelve -s {cl} -f\" )" and f"[Error]: 'Change {cl} is already committed.'" but the Universum output just f"Change {cl} is already committed.".
The suggested solution is to change the name of the test to `test_p4_print_exception_already_committed_shelve` and the value of `pattern_to_search`.
**The reason is the new error output in p4python 2024.1.0.** …
=> fix(tests): Fixes for p4 unit tests

tests/test_code_report.py, universum/modules/code_report_collector.py
Detekt has changed uri format for its sarif report to explicitly define file:/// schema: https://github.com/detekt/detekt/pull/6331/files
It seems Universum can't parse these updated links.
We need to modify core_report_collector to parse uri instead of just unquoting it.
=> fix(report): Parse data from sarif as URI
